const db = require("../config/db");
const { klientBazy } = require("../config/db");

let tabelaNotatekGotowa = false;

async function zapewnijTabeleNotatek() {
  if (tabelaNotatekGotowa) return;

  if (klientBazy === "postgres") {
    await db.query(`
      CREATE TABLE IF NOT EXISTS panel_notatki (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tytul VARCHAR(220) NOT NULL,
        tresc TEXT,
        termin_at TIMESTAMP NULL,
        created_by INTEGER NULL REFERENCES uzytkownicy(id) ON DELETE SET NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW()
      )
    `);

    await db.query(`
      CREATE OR REPLACE FUNCTION ustaw_panel_notatki_updated_at()
      RETURNS TRIGGER AS $$
      BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `);

    await db.query("DROP TRIGGER IF EXISTS trg_panel_notatki_updated_at ON panel_notatki");
    await db.query(`
      CREATE TRIGGER trg_panel_notatki_updated_at
      BEFORE UPDATE ON panel_notatki
      FOR EACH ROW
      EXECUTE FUNCTION ustaw_panel_notatki_updated_at()
    `);
  } else {
    await db.query(`
      CREATE TABLE IF NOT EXISTS panel_notatki (
        id INT AUTO_INCREMENT PRIMARY KEY,
        tytul VARCHAR(220) NOT NULL,
        tresc TEXT,
        termin_at DATETIME NULL,
        created_by INT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CONSTRAINT fk_panel_notatki_uzytkownik FOREIGN KEY (created_by) REFERENCES uzytkownicy(id) ON DELETE SET NULL
      )
    `);
  }

  tabelaNotatekGotowa = true;
}

async function pobierzPanelGlowny(_req, res) {
  await zapewnijTabeleNotatek();
  const licznik = await db.query("SELECT COUNT(*) AS liczba FROM protokoly");
  const dokumenty = await db.query(
    "SELECT id, numer_protokolu, data, klient, created_at FROM protokoly ORDER BY created_at DESC LIMIT 5"
  );
  const notatki = await db.query(
    `SELECT n.id, n.tytul, n.tresc, n.termin_at, n.created_at, n.updated_at, n.created_by, u.imie_nazwisko
     FROM panel_notatki n
     LEFT JOIN uzytkownicy u ON u.id = n.created_by
     ORDER BY
       CASE WHEN n.termin_at IS NULL THEN 1 ELSE 0 END,
       n.termin_at ASC,
       n.created_at DESC
     LIMIT 12`
  );

  return res.json({
    liczbaProtokolow: Number(licznik.rows[0].liczba),
    ostatnioUtworzoneDokumenty: dokumenty.rows,
    notatki: notatki.rows
  });
}

async function utworzNotatke(req, res) {
  await zapewnijTabeleNotatek();

  const tytul = String(req.body?.tytul || "").trim();
  const tresc = String(req.body?.tresc || "").trim();
  const termin = String(req.body?.termin_at || "").trim();

  if (!tytul) {
    return res.status(400).json({ blad: "Podaj tytuł notatki." });
  }

  const insert = await db.query(
    `INSERT INTO panel_notatki(tytul, tresc, termin_at, created_by)
     VALUES(?,?,?,?)`,
    [tytul, tresc || null, termin || null, req.uzytkownik?.id || null]
  );

  const id = insert.rows.insertId;
  const wynik = await db.query(
    `SELECT n.id, n.tytul, n.tresc, n.termin_at, n.created_at, n.updated_at, n.created_by, u.imie_nazwisko
     FROM panel_notatki n
     LEFT JOIN uzytkownicy u ON u.id = n.created_by
     WHERE n.id = ?`,
    [id]
  );

  return res.status(201).json(wynik.rows[0]);
}

async function usunNotatke(req, res) {
  await zapewnijTabeleNotatek();
  const wynik = await db.query("DELETE FROM panel_notatki WHERE id = ?", [req.params.id]);

  if (!wynik.rows.affectedRows) {
    return res.status(404).json({ blad: "Nie znaleziono notatki." });
  }

  return res.json({ komunikat: "Notatka została usunięta." });
}

module.exports = { pobierzPanelGlowny, utworzNotatke, usunNotatke };
